#!/bin/bash
# Re-run every best setting from docs/PhaseFormer_L_best_settings_repro.md.
# --resume makes each a no-op where the artifact already exists.
set -u
PY=/home/yyk/yyk03/miniconda3/envs/time/bin/python
cd ~/niuyiming/PhaseFormer || exit 1
echo '=== [1/8]'; CUDA_VISIBLE_DEVICES=0 $PY scripts/search_phaseformer.py --output-dir research_runs/phaseformer_L_golden_search_v1/runs/ETTh1-h96_s2021_g0.2_lr0.003_r24_mae --dataset ETTh1 --horizon 96 --stage confirm --lookback 720 --period 24 --max-epochs 30 --seed 2021 --loss mae --percent 100 --require-cuda --resume --num-workers 4 --bad-case-limit 0 --mechanism weak_residual --learning-rate 0.003 --overrides '{"learning_rate": 0.003, "weak_period_residual_gate_init": 0.2, "weak_period_residual_head_type": "pooled_lowrank", "weak_period_residual_pool_factor": 1, "weak_period_residual_rank": 24}' --evaluate-test
echo '=== [2/8]'; CUDA_VISIBLE_DEVICES=1 $PY scripts/search_phaseformer.py --output-dir research_runs/phaseformer_L_golden_search_v1/runs/ETTm1-h96_s2021_g0.1_lr0.001_r12_mae --dataset ETTm1 --horizon 96 --stage confirm --lookback 720 --period 24 --max-epochs 30 --seed 2021 --loss mae --percent 100 --require-cuda --resume --num-workers 4 --bad-case-limit 0 --mechanism weak_residual --learning-rate 0.001 --overrides '{"learning_rate": 0.001, "weak_period_residual_gate_init": 0.1, "weak_period_residual_head_type": "pooled_lowrank", "weak_period_residual_pool_factor": 1, "weak_period_residual_rank": 12}' --evaluate-test
echo '=== [3/8]'; CUDA_VISIBLE_DEVICES=2 $PY scripts/search_phaseformer.py --output-dir research_runs/phaseformer_L_golden_search_v1/runs/Electricity-h96_s2021_g0.2_lr0.003_r24 --dataset Electricity --horizon 96 --stage confirm --lookback 720 --period 24 --max-epochs 30 --seed 2021 --loss huber --percent 100 --require-cuda --resume --num-workers 4 --bad-case-limit 0 --mechanism weak_residual --learning-rate 0.003 --overrides '{"learning_rate": 0.003, "weak_period_residual_gate_init": 0.2, "weak_period_residual_head_type": "pooled_lowrank", "weak_period_residual_pool_factor": 1, "weak_period_residual_rank": 24}' --evaluate-test
echo '=== [4/8]'; CUDA_VISIBLE_DEVICES=3 $PY scripts/search_phaseformer.py --output-dir research_runs/phaseformer_L_golden_search_v1/runs/ETTh1-h192_s2021_g0.02_lr0.001_r6_mae --dataset ETTh1 --horizon 192 --stage confirm --lookback 720 --period 24 --max-epochs 30 --seed 2021 --loss mae --percent 100 --require-cuda --resume --num-workers 4 --bad-case-limit 0 --mechanism weak_residual --learning-rate 0.001 --overrides '{"learning_rate": 0.001, "weak_period_residual_gate_init": 0.02, "weak_period_residual_head_type": "pooled_lowrank", "weak_period_residual_pool_factor": 1, "weak_period_residual_rank": 6}' --evaluate-test
echo '=== [5/8]'; CUDA_VISIBLE_DEVICES=4 $PY scripts/search_phaseformer.py --output-dir research_runs/phaseformer_L_golden_search_v1/runs/ETTm1-h192_s2023_g0.2_lr0.0003_r6_mae --dataset ETTm1 --horizon 192 --stage confirm --lookback 720 --period 24 --max-epochs 30 --seed 2023 --loss mae --percent 100 --require-cuda --resume --num-workers 4 --bad-case-limit 0 --mechanism weak_residual --learning-rate 0.0003 --overrides '{"learning_rate": 0.0003, "weak_period_residual_gate_init": 0.2, "weak_period_residual_head_type": "pooled_lowrank", "weak_period_residual_pool_factor": 1, "weak_period_residual_rank": 6}' --evaluate-test
echo '=== [6/8]'; CUDA_VISIBLE_DEVICES=5 $PY scripts/search_phaseformer.py --output-dir research_runs/phaseformer_L_golden_search_v1/runs/ETTh1-h336_s2021_g0.02_lr0.01_r21_d0.1 --dataset ETTh1 --horizon 336 --stage confirm --lookback 720 --period 24 --max-epochs 30 --seed 2021 --loss huber --percent 100 --require-cuda --resume --num-workers 4 --bad-case-limit 0 --mechanism weak_residual --learning-rate 0.01 --overrides '{"huber_delta": 0.1, "learning_rate": 0.01, "weak_period_residual_gate_init": 0.02, "weak_period_residual_head_type": "pooled_lowrank", "weak_period_residual_pool_factor": 1, "weak_period_residual_rank": 21}' --evaluate-test
echo '=== [7/8]'; CUDA_VISIBLE_DEVICES=6 $PY scripts/search_phaseformer.py --output-dir research_runs/phaseformer_L_golden_search_v1/runs/ETTm1-h336_s2021_g0.2_lr0.0003_r10_mae --dataset ETTm1 --horizon 336 --stage confirm --lookback 720 --period 24 --max-epochs 30 --seed 2021 --loss mae --percent 100 --require-cuda --resume --num-workers 4 --bad-case-limit 0 --mechanism weak_residual --learning-rate 0.0003 --overrides '{"learning_rate": 0.0003, "weak_period_residual_gate_init": 0.2, "weak_period_residual_head_type": "pooled_lowrank", "weak_period_residual_pool_factor": 1, "weak_period_residual_rank": 10}' --evaluate-test
echo '=== [8/8]'; CUDA_VISIBLE_DEVICES=7 $PY scripts/search_phaseformer.py --output-dir research_runs/phaseformer_L_golden_search_v1/runs/ETTm1-h720_s2021_g0.1_lr0.0003_r45_mae --dataset ETTm1 --horizon 720 --stage confirm --lookback 720 --period 24 --max-epochs 30 --seed 2021 --loss mae --percent 100 --require-cuda --resume --num-workers 4 --bad-case-limit 0 --mechanism weak_residual --learning-rate 0.0003 --overrides '{"learning_rate": 0.0003, "weak_period_residual_gate_init": 0.1, "weak_period_residual_head_type": "pooled_lowrank", "weak_period_residual_pool_factor": 1, "weak_period_residual_rank": 45}' --evaluate-test
echo '=== all 8 settings replayed'
